### ISSUE TITLE
`max-pure` does require C-toolchain

### ISSUE THREAD

**Issue by jarkkojs** [Byron/gitoxide#1121]
### Current behavior 😯

```
$ cargo init gitoxide-test
     Created binary (application) package

$ cd gitoxide-test/

$ cargo add gitoxide --features=max-pure
    Updating crates.io index
      Adding gitoxide v0.31.1 to dependencies.
             Features:
             + crosstermion
             + fast
             + fast-safe
             + futures-lite
             + gitoxide-core-blocking-client
             + gitoxide-core-tools
             + gitoxide-core-tools-archive
             + gitoxide-core-tools-corpus
             + gitoxide-core-tools-query
             + http-client-curl
             + http-client-reqwest
             + is-terminal
             + max
             + max-control
             + max-pure
             + pretty-cli
             + prodash-render-line
             + prodash-render-line-crossterm
             + prodash-render-tui
             + tracing
             - cache-efficiency-debug
             - document-features
             - gitoxide-core-async-client
             - lean
             - lean-async
             - prodash
             - small
    Updating crates.io index

$ cargo b
   Compiling libc v0.2.150
   Compiling proc-macro2 v1.0.69
   Compiling unicode-ident v1.0.12
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling serde v1.0.192
   Compiling once_cell v1.18.0
   Compiling memchr v2.6.4
   Compiling log v0.4.20
   Compiling thiserror v1.0.50
   Compiling version_check v0.9.4
   Compiling futures-core v0.3.29
   Compiling pin-project-lite v0.2.13
   Compiling scopeguard v1.2.0
   Compiling crossbeam-utils v0.8.16
   Compiling itoa v1.0.9
   Compiling parking_lot_core v0.9.9
   Compiling futures-io v0.3.29
   Compiling bytes v1.5.0
   Compiling regex-syntax v0.8.2
   Compiling futures-sink v0.3.29
   Compiling futures-channel v0.3.29
   Compiling signal-hook v0.3.17
   Compiling typenum v1.17.0
   Compiling bitflags v1.3.2
   Compiling powerfmt v0.2.0
   Compiling rustix v0.38.24
   Compiling time-core v0.1.2
   Compiling num_threads v0.1.6
   Compiling linux-raw-sys v0.4.11
   Compiling unicode-width v0.1.11
   Compiling event-listener v2.5.3
   Compiling io-lifetimes v1.0.11
   Compiling fastrand v1.9.0
   Compiling waker-fn v1.1.1
   Compiling rayon-core v1.12.0
   Compiling time-macros v0.2.15
   Compiling rustix v0.37.27
   Compiling crossbeam-queue v0.3.8
   Compiling cassowary v0.3.0
   Compiling unicode-segmentation v1.10.1
   Compiling parking v2.2.0
   Compiling tracing-core v0.1.32
   Compiling deranged v0.3.9
   Compiling crc32fast v1.3.2
   Compiling adler v1.0.2
   Compiling either v1.9.0
   Compiling linux-raw-sys v0.3.8
   Compiling async-lock v2.8.0
   Compiling humantime v2.1.0
   Compiling miniz_oxide v0.7.1
   Compiling ansi_term v0.12.1
   Compiling human_format v1.0.3
   Compiling same-file v1.0.6
   Compiling generic-array v0.14.7
   Compiling cpufeatures v0.2.11
   Compiling sha1_smol v1.0.0
   Compiling ahash v0.8.6
   Compiling zerocopy v0.7.26
   Compiling lock_api v0.4.11
   Compiling slab v0.4.9
   Compiling memoffset v0.9.0
   Compiling crossbeam-epoch v0.9.15
   Compiling polling v2.8.0
   Compiling async-io v1.13.0
   Compiling gix-trace v0.1.3
   Compiling walkdir v2.4.0
   Compiling num-traits v0.2.17
   Compiling allocator-api2 v0.2.16
   Compiling home v0.5.5
   Compiling pkg-config v0.3.27
   Compiling vcpkg v0.2.15
   Compiling concurrent-queue v2.3.0
   Compiling futures-lite v1.13.0
   Compiling crossbeam-channel v0.5.8
   Compiling winnow v0.5.19
   Compiling fastrand v2.0.1
   Compiling tinyvec_macros v0.1.1
   Compiling futures-task v0.3.29
   Compiling quote v1.0.33
   Compiling tinyvec v1.6.0
   Compiling async-channel v1.9.0
   Compiling percent-encoding v2.3.0
   Compiling unicode-bom v2.0.3
   Compiling futures-util v0.3.29
   Compiling fnv v1.0.7
   Compiling static_assertions v1.1.0
   Compiling unicode-bidi v0.3.13
   Compiling pin-utils v0.1.0
   Compiling form_urlencoded v1.2.0
   Compiling gix-utils v0.1.5
   Compiling syn v2.0.39
   Compiling untrusted v0.9.0
   Compiling spin v0.9.8
   Compiling heck v0.4.1
   Compiling crossbeam-deque v0.8.3
   Compiling encoding_rs v0.8.33
   Compiling http v0.2.11
   Compiling rustls v0.21.9
   Compiling httparse v1.8.0
   Compiling equivalent v1.0.1
   Compiling async-trait v0.1.74
   Compiling ppv-lite86 v0.2.17
   Compiling try-lock v0.2.4
   Compiling match_cfg v0.1.0
   Compiling httpdate v1.0.3
   Compiling want v0.3.1
   Compiling linked-hash-map v0.5.6
   Compiling ipnet v2.9.0
   Compiling crossbeam v0.8.2
   Compiling quick-error v1.2.3
   Compiling tower-service v0.3.2
   Compiling cc v1.0.83
   Compiling data-encoding v2.4.0
   Compiling ryu v1.0.15
   Compiling base64 v0.21.5
   Compiling hashbrown v0.12.3
   Compiling syn v1.0.109
   Compiling mio v0.8.9
   Compiling signal-hook-registry v1.4.1
   Compiling socket2 v0.4.10
   Compiling getrandom v0.2.11
   Compiling memmap2 v0.7.1
   Compiling num_cpus v1.16.0
   Compiling socket2 v0.5.5
   Compiling rand_core v0.6.4
   Compiling filetime v0.2.22
   Compiling regex-automata v0.4.3
   Compiling unicode-normalization v0.1.22
   Compiling rand_chacha v0.3.1
   Compiling hostname v0.3.1
   Compiling lru-cache v0.1.2
   Compiling curl v0.4.44
   Compiling signal-hook-mio v0.2.3
   Compiling resolv-conf v0.7.0
   Compiling rayon v1.8.0
   Compiling hashbrown v0.14.2
   Compiling tokio v1.34.0
   Compiling http-body v0.4.5
   Compiling rand v0.8.5
   Compiling cmake v0.1.50
   Compiling time v0.3.30
   Compiling btoi v0.4.3
   Compiling imara-diff v0.1.5
   Compiling rustls-pemfile v1.0.4
   Compiling openssl-probe v0.1.5
   Compiling utf8parse v0.2.1
   Compiling webpki-roots v0.25.2
   Compiling arrayvec v0.7.4
   Compiling mime v0.3.17
   Compiling anstyle-parse v0.2.2
   Compiling xattr v1.0.1
   Compiling anstyle v1.0.4
   Compiling colorchoice v1.0.0
   Compiling overload v0.1.1
   Compiling block-buffer v0.10.4
   Compiling crypto-common v0.1.6
   Compiling byteorder v1.5.0
   Compiling anstyle-query v1.0.0
   Compiling uluru v3.0.0
   Compiling clru v0.6.1
   Compiling lazy_static v1.4.0
   Compiling anstream v0.6.4
   Compiling digest v0.10.7
   Compiling tar v0.4.40
   Compiling nu-ansi-term v0.46.0
   Compiling idna v0.4.0
   Compiling sharded-slab v0.1.7
   Compiling io-close v0.3.7
   Compiling tracing-log v0.2.0
   Compiling fs-err v2.10.0
   Compiling is-docker v0.2.0
   Compiling thread_local v1.1.7
   Compiling strsim v0.10.0
   Compiling anyhow v1.0.75
   Compiling serde_json v1.0.108
   Compiling clap_lex v0.6.0
   Compiling arc-swap v1.6.0
   Compiling is-wsl v0.4.0
   Compiling fallible-streaming-iterator v0.1.9
   Compiling fallible-iterator v0.2.0
   Compiling pathdiff v0.2.1
   Compiling clap_builder v4.4.8
   Compiling indexmap v2.1.0
   Compiling hashlink v0.8.4
   Compiling bytecount v0.6.7
   Compiling open v5.0.0
   Compiling sysinfo v0.29.10
   Compiling itertools v0.11.0
   Compiling termcolor v1.4.0
   Compiling papergrid v0.7.1
   Compiling layout-rs v0.1.1
   Compiling owo-colors v3.5.0
   Compiling libz-ng-sys v1.1.12
   Compiling sha1-asm v0.5.2
   Compiling ring v0.17.5
   Compiling url v2.4.1
   Compiling libz-sys v1.1.12
   Compiling openssl-sys v0.9.95
   Compiling curl-sys v0.4.68+curl-8.4.0
   Compiling libsqlite3-sys v0.26.0
error: failed to run custom build command for `libz-ng-sys v1.1.12`

Caused by:
  process didn't exit successfully: `/home/jarkko/work/gitoxide-test/target/debug/build/libz-ng-sys-fb7d52706df2a3ee/build-script-build_zng` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/home/jarkko/work/gitoxide-test/target/debug/build/libz-ng-sys-a044ac41ca740c8a/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/jarkko/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libz-ng-sys-1.1.12/src/zlib-ng" "-DBUILD_SHARED_LIBS=OFF" "-DZLIB_COMPAT=OFF" "-DZLIB_ENABLE_TESTS=OFF" "-DWITH_GZFILEOP=ON" "-DCMAKE_INSTALL_PREFIX=/home/jarkko/work/gitoxide-test/target/debug/build/libz-ng-sys-a044ac41ca740c8a/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  thread 'main' panicked at /home/jarkko/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

### Expected behavior 🤔

Neither `cmake` nor C-compiler required.

**Comment by jarkkojs** [comment]
So I guess this should use something like https://github.com/kawasin73/prsqlite in order to be pure Rust?

**Comment by Byron** [comment]
Are default features disabled?
Max-pure is tested, and cmaje is definitely not required for it.

**Comment by jarkkojs** [comment]
> cargo add gitoxide --features=max-pure

You can see the exact transcript above, i.e.

```
cargo init blankproject
cd blankproject
cargo add gitoxide --features=max-pure
cargo b
```

Fails with:

```
   Compiling libsqlite3-sys v0.26.0
error: failed to run custom build command for `libz-ng-sys v1.1.12`

Caused by:
  process didn't exit successfully: `/home/jarkko/work/gitoxide-test/target/debug/build/libz-ng-sys-fb7d52706df2a3ee/build-script-build_zng` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/home/jarkko/work/gitoxide-test/target/debug/build/libz-ng-sys-a044ac41ca740c8a/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/jarkko/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libz-ng-sys-1.1.12/src/zlib-ng" "-DBUILD_SHARED_LIBS=OFF" "-DZLIB_COMPAT=OFF" "-DZLIB_ENABLE_TESTS=OFF" "-DWITH_GZFILEOP=ON" "-DCMAKE_INSTALL_PREFIX=/home/jarkko/work/gitoxide-test/target/debug/build/libz-ng-sys-a044ac41ca740c8a/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  thread 'main' panicked at /home/jarkko/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by jarkkojs** [comment]
Maybe the bug triggers only when using gitoxide as an external crate?

**Comment by NobodyXu** [comment]
Can you try disabling default features?

**Comment by jarkkojs** [comment]
> Can you try disabling default features of gitoxide?

So the target `max-pure` pulls also `max`:

```
$ cargo add gitoxide --features=max-pure
    Updating crates.io index
      Adding gitoxide v0.31.1 to dependencies.
             Features:
             + crosstermion
             + fast
             + fast-safe
             + futures-lite
             + gitoxide-core-blocking-client
             + gitoxide-core-tools
             + gitoxide-core-tools-archive
             + gitoxide-core-tools-corpus
             + gitoxide-core-tools-query
             + http-client-curl
             + http-client-reqwest
             + is-terminal
             + max
             + max-control
             + max-pure
             + pretty-cli
             + prodash-render-line
             + prodash-render-line-crossterm
             + prodash-render-tui
             + tracing
             - cache-efficiency-debug
             - document-features
             - gitoxide-core-async-client
             - lean
             - lean-async
             - prodash
             - small
    Updating crates.io index
```

What would be the right flag for `max-pure` build if selecting `max-pure` does not lead to `max-pure` build. I'm a bit confused tbh.

**Comment by Skgland** [comment]
I think the CLI invocation would be `cargo add gitoxide --features=max-pure --no-default-features` to disable default features.

**Comment by Byron** [comment]
Thanks everyone for chiming in helping in the matter. I think @Skgland puts it very concisely and there is nothing I can add but to strongly recommend against using `gitoxide` as a library, as it's meant to provide the `gix` and `ein` binaries, and nothing else.

To use `gitoxide` (the project) in an application, one uses the `gix` crate as entry point. And if one wishes to re-use the higher-level commands exposed by the `gix` binary (the CLI), one would use the `gitoxide-core` crate. Even that isn't recommended though as it will be unstable probably forever. `gix`, the crate, is what eventually will be stabilized though and it's meant for use in applications.

It's a little bit confusing, yet I hope this explanation sheds some light on the matter.

Closing, as this is an issue with the way `cargo` is invoked and the dependency is configured - `default-features` have to be disabled.

**Comment by jarkkojs** [comment]
OK, thanks for educating with this and sorry for the late response :-)
