### ISSUE TITLE
`cargo smart-release` panics: "index out of bounds: the len is 145 but the index is 145"

### ISSUE THREAD

**Issue by dyc3** [Byron/gitoxide#174]
Repo: https://github.com/dyc3/steamguard-cli

Command:
```
cargo smart-release
```

Output:
```
[WARN ] Consider running with --update-crates-index to assure bumping on demand uses the latest information
[WARN ] Using 'steamguard-cli' as crate name as no one was provided. Specify one if this isn't correct
thread 'main' panicked at 'index out of bounds: the len is 145 but the index is 145', /home/carson/.cargo/registry/src/github.com-1ecc6299db9ec823/git-ref-0.5.3/src/store/packed/find.rs:74:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:69:5
   3: git_ref::store::packed::find::<impl git_ref::store::packed::Buffer>::binary_search_by
   4: git_ref::store::packed::find::<impl git_ref::store::packed::Buffer>::find
   5: git_ref::store::file::find::<impl git_ref::store::file::Store>::find_inner
   6: git_ref::store::file::find::<impl git_ref::store::file::Store>::find_one_with_verified_input
   7: git_ref::store::file::find::<impl git_ref::store::file::Store>::find
   8: cargo_smart_release::command::release_impl::git::has_changed_since_last_release
   9: cargo_smart_release::command::release_impl::depth_first_traversal
  10: cargo_smart_release::command::release_impl::release
  11: cargo_smart_release::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Byron** [comment]
Thanks for the report. I ran into it as well and fixed it. Which version are you using? I would hope I published the fix already. 0.2.4 is the latest on crates.io.

**Comment by dyc3** [comment]
I just did a `cargo install` again this morning, I'm on v0.2.4.

**Comment by Byron** [comment]
Sorry for that. I will create a new release very soon and update this issue when done.

For reference, this is an issue with a bug (missing test) for doing a binary search of packed-refs. Tests never ran into the issue where the searched name was larger than all names in the packed-refs file.

**Comment by Byron** [comment]
Oh, btw, you could verify it actually works on main with something like this

```
cargo install --git https://github.com/Byron/gitoxide --package cargo-smart-release
```

**Comment by dyc3** [comment]
That command is giving me this:

```
error: Found argument '--package' which wasn't expected, or isn't valid in this context

USAGE:
    cargo install --git <URL>

For more information try --help
```

**Comment by dyc3** [comment]
I cloned and installed from source and it works.
