### ISSUE TITLE
thread 'thread 'gitoxide.in_parallel.produce.8' panicked at 'not yet implemented'

### ISSUE THREAD

**Issue by yonas** [Byron/gitoxide#781]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

```
$ gix clone https://github.com/getdnsapi/getdns
 14:49:22 read pack done 11.8MB in 1.52s (7.8MB/s)                                                                                                                                                                   
 14:49:22  indexing done 19.2k objects in 1.46s (13.2k objects/s)                                                                                                                                                    
 14:49:22 decompressing done 26.5MB in 1.46s (18.2MB/s)                                                                                                                                                              
 14:49:22     Resolving done 19.2k objects in 0.32s (60.3k objects/s)                                                                                                                                                
 14:49:22      Decoding done 280.6MB in 0.32s (880.9MB/s)                                                                                                                                                            
 14:49:22 writing index file done 538.6KB in 0.00s (132.8MB/s)                                                                                                                                                       
 14:49:22  create index file done 19.2k objects in 1.79s (10.7k objects/s)                                                                                                                                           
thread 'gitoxide.in_parallel.produce.11thread 'gitoxide.in_parallel.produce.13' panicked at 'not yet implemented', /memfs/git/gitoxide/gix-worktree/src/index/entry.rs:101:43===   ===   ===   ===   ===   ===   ===]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
' panicked at 'not yet implemented', /memfs/git/gitoxide/gix-worktree/src/index/entry.rs:101:43
thread 'gitoxide.in_parallel.produce.15' panicked at 'not yet implemented', /memfs/git/gitoxide/gix-worktree/src/index/entry.rs:101:43
thread 'main' panicked at 'a scoped thread panicked', /memfs/git/gitoxide/gix-features/src/parallel/in_parallel.rs:59:5
```

### Expected behavior 🤔

Should not crash.

### Steps to reproduce 🕹

Run `gix clone https://github.com/getdnsapi/getdns`

```
$ gix --version
gix-plumbing 0.24.0
```

**Comment by Byron** [comment]
'not yet implemented' indicates that a codepath was hit that is still to be implemented.  `gix` being a tool to aid the development of `gitoxide` and is actively in development, that's an acceptable practice.

Over the next couple of months worktree checkouts will be completely implemented which will resolve the problem.
